// Copies the desktop app's renderer into this site so the in-page demo runs the
// real windows instead of a re-creation of them.
//
//   node scripts/sync-demo.mjs [path-to-ClauMeter-app]
//
// The app repo is not a dependency of this one (Cloudflare Pages only ever sees
// this repo), so the copies in public/demo/ are committed. Re-run this whenever
// the app's renderer changes, then commit the diff — a diff is exactly what you
// want to see here, because it tells you the demo drifted.
//
// Everything the app owns is copied byte-for-byte. The only edits are:
//   - one <script src="bridge.js"> injected ahead of each page's own scripts,
//     which is what stands in for Electron's preload (see public/demo/bridge.js)
//   - locales.js turned from CommonJS into an ES module so Vite can import it
//
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const APP = resolve(ROOT, process.argv[2] ?? '../../ClauMeter/ClauMeter')
const OUT = join(ROOT, 'public', 'demo')
const SRC_OUT = join(ROOT, 'src', 'demo')

if (!existsSync(join(APP, 'renderer', 'index.html'))) {
  console.error(`No ClauMeter app renderer at ${APP}\nUsage: node scripts/sync-demo.mjs [path-to-app]`)
  process.exit(1)
}

const BANNER = (from) =>
  `// GENERATED by scripts/sync-demo.mjs from the ClauMeter app (${from}).\n` +
  `// Do not edit here — edit the app and re-run the script.\n`

// Replaces exactly one occurrence, and fails loudly if the anchor has moved.
function swap(text, anchor, replacement, what) {
  const at = text.indexOf(anchor)
  if (at === -1) throw new Error(`sync-demo: could not find ${what} in the app source:\n  ${anchor}`)
  if (text.indexOf(anchor, at + 1) !== -1) throw new Error(`sync-demo: ${what} appears more than once`)
  return text.slice(0, at) + replacement + text.slice(at + anchor.length)
}

mkdirSync(OUT, { recursive: true })
mkdirSync(SRC_OUT, { recursive: true })

// --- the three windows' scripts, verbatim -----------------------------------
for (const f of ['renderer.js', 'detail.js', 'calibrate.js', 'flags.js']) {
  copyFileSync(join(APP, 'renderer', f), join(OUT, f))
}

// --- the three windows' markup, with the demo bridge in front ---------------
const BRIDGE = '<script src="bridge.js"></script>\n  '
const PAGES = [
  ['index.html', 'widget.html', '<script src="renderer.js"></script>'],
  ['detail.html', 'detail.html', '<script src="detail.js"></script>'],
  ['calibrate.html', 'calibrate.html', '<script src="flags.js"></script>'],
]
for (const [from, to, anchor] of PAGES) {
  const html = readFileSync(join(APP, 'renderer', from), 'utf8')
  writeFileSync(join(OUT, to), swap(html, anchor, BRIDGE + anchor, `the script tag of ${from}`))
}

// --- locales.js, as an ES module -------------------------------------------
const CJS = 'module.exports = { LOCALES, SUPPORTED_LANGUAGES, LANGUAGE_NAME_EN, DEFAULT_LANGUAGE, t };'
const ESM = 'export { LOCALES, SUPPORTED_LANGUAGES, LANGUAGE_NAME_EN, DEFAULT_LANGUAGE, t };'
const locales = readFileSync(join(APP, 'locales.js'), 'utf8')
writeFileSync(
  join(SRC_OUT, 'locales.js'),
  BANNER('locales.js') + swap(locales, CJS, ESM, 'the module.exports of locales.js')
)

console.log(`Synced the demo from ${APP}`)
console.log(`  public/demo/  widget.html detail.html calibrate.html + 4 scripts`)
console.log(`  src/demo/     locales.js`)
